# Generated by Django 3.2.8 on 2021-10-25 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conversionCSVTTL', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Document',
        ),
    ]
