# Generated by Django 3.2.8 on 2021-10-26 13:13

import conversionCSVTTL.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionCSVTTL', '0004_alter_document_csvfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='CSVfile',
            field=models.FileField(upload_to='CSVfiles', validators=[conversionCSVTTL.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='document',
            name='delimitation',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='title_row',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
