# Generated by Django 3.2.8 on 2021-10-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionCSVTTL', '0008_auto_20211027_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='file_name',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='information',
            name='prefix_pred',
            field=models.CharField(default='@prefix p: <http://ex.org/pred#> .\n\n', max_length=25),
        ),
        migrations.AlterField(
            model_name='information',
            name='prefix_subj',
            field=models.CharField(default='@prefix d: <http://ex.org/data/> .\n', max_length=25),
        ),
    ]
