# Generated by Django 3.2.8 on 2021-10-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversionCSVTTL', '0010_auto_20211027_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='delimiter',
            field=models.CharField(blank=True, default=',', max_length=1),
        ),
        migrations.AddField(
            model_name='information',
            name='path_to_csv',
            field=models.CharField(default='', max_length=25),
        ),
    ]
